# Generated by Django 6.0.2 on 2026-03-31 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'db_table': 'endereco',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao', models.CharField(max_length=100, verbose_name='Órgão/Empresa')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('ativo', models.BooleanField(default=True)),
                ('nome_contato', models.CharField(max_length=100, verbose_name='Nome do Contato')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='associado.endereco')),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associados', to='associado.empresa')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associados', to='associado.endereco')),
            ],
            options={
                'db_table': 'associado',
            },
        ),
    ]
