# Generated by Django 6.0.2 on 2026-04-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associado',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='endereco',
        ),
        migrations.AddField(
            model_name='endereco',
            name='associado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='associado.associado'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='empresa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='associado.empresa'),
        ),
    ]
