# Generated by Django 6.0.2 on 2026-04-02 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoAssociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('associado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='associado.associado')),
            ],
            options={
                'db_table': 'endereco_associado',
            },
        ),
        migrations.CreateModel(
            name='EnderecoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='associado.empresa')),
            ],
            options={
                'db_table': 'endereco_empresa',
            },
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
