# Generated by Django 6.0.2 on 2026-03-25 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('associado', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='associado',
            table='associado',
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='empresa',
        ),
    ]
